'use client';

import { motion } from 'framer-motion';
import { TrophyIcon, SparklesIcon, ArrowPathIcon, DocumentArrowDownIcon } from '@heroicons/react/24/solid';
import { Button } from './ui/Button';
import { DraftOrder } from '@/types';
import jsPDF from 'jspdf';

interface ResultsPhaseProps {
  draftOrder: DraftOrder[];
  onRestart: () => void;
}

export function ResultsPhase({ draftOrder, onRestart }: ResultsPhaseProps) {
  // Sort by draft position
  const sortedOrder = [...draftOrder].sort((a, b) => a.position - b.position);

  const exportToPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;
    
    // Title
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Fantasy Football 2025 - Final Draft Order', pageWidth / 2, 30, { align: 'center' });
    
    // Subtitle
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    const currentDate = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
    doc.text(`Generated on ${currentDate}`, pageWidth / 2, 40, { align: 'center' });
    
    // Header line
    doc.setLineWidth(0.5);
    doc.line(margin, 50, pageWidth - margin, 50);
    
    let yPosition = 70;
    
    sortedOrder.forEach((pick, index) => {
      // Check if we need a new page
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
      
      // Position number (large and bold)
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(`#${pick.position}`, margin, yPosition);
      
      // Medal emoji for top 3
      let medal = '';
      if (pick.position === 1) medal = '🥇';
      else if (pick.position === 2) medal = '🥈';
      else if (pick.position === 3) medal = '🥉';
      
      if (medal) {
        doc.setFontSize(12);
        doc.text(medal, margin + 25, yPosition);
      }
      
      // Name and Team (main info)
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(pick.name, margin + 40, yPosition);
      
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.text(`Team: ${pick.team}`, margin + 40, yPosition + 8);
      
      // Strategy
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Strategy:', margin + 40, yPosition + 18);
      doc.setFont('helvetica', 'normal');
      doc.text(pick.strategy, margin + 70, yPosition + 18);
      
      // Motto
      doc.setFont('helvetica', 'bold');
      doc.text('Motto:', margin + 40, yPosition + 26);
      doc.setFont('helvetica', 'italic');
      const motto = `"${pick.motto}"`;
      const wrappedMotto = doc.splitTextToSize(motto, pageWidth - margin - 80);
      doc.text(wrappedMotto, margin + 70, yPosition + 26);
      
      // Prediction
      const mottoHeight = Array.isArray(wrappedMotto) ? wrappedMotto.length * 4 : 4;
      doc.setFont('helvetica', 'bold');
      doc.text('Prediction:', margin + 40, yPosition + 34 + mottoHeight);
      doc.setFont('helvetica', 'italic');
      const prediction = `"${pick.prediction}"`;
      const wrappedPrediction = doc.splitTextToSize(prediction, pageWidth - margin - 80);
      doc.text(wrappedPrediction, margin + 70, yPosition + 34 + mottoHeight);
      
      // Separator line
      const predictionHeight = Array.isArray(wrappedPrediction) ? wrappedPrediction.length * 4 : 4;
      yPosition += 50 + mottoHeight + predictionHeight;
      
      if (index < sortedOrder.length - 1) {
        doc.setLineWidth(0.2);
        doc.line(margin, yPosition - 10, pageWidth - margin, yPosition - 10);
      }
    });
    
    // Footer
    const pageCount = doc.internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, 285, { align: 'center' });
      doc.text('Generated by Fantasy Draft Revealer', pageWidth / 2, 290, { align: 'center' });
    }
    
    // Save the PDF
    doc.save(`Fantasy_Draft_Order_${new Date().getFullYear()}.pdf`);
  };

  const getPositionColor = (position: number) => {
    switch (position) {
      case 1: return 'from-yellow-400 to-amber-500';
      case 2: return 'from-gray-300 to-gray-400';
      case 3: return 'from-amber-600 to-yellow-700';
      default: return 'from-slate-400 to-slate-500';
    }
  };

  const getPositionEmoji = (position: number) => {
    switch (position) {
      case 1: return '🥇';
      case 2: return '🥈';
      case 3: return '🥉';
      default: return '🏆';
    }
  };

  return (
    <div className="container mx-auto px-4 py-8 max-w-6xl">
      {/* Header - Match RevealPhase styling */}
      <motion.div 
        className="text-center mb-12 backdrop-blur-xl bg-slate-900/50 rounded-3xl p-8 border border-yellow-500/20 shadow-2xl"
        initial={{ opacity: 0, y: -30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
      >
        <div className="flex items-center justify-center gap-4 mb-6">
          <motion.div 
            animate={{ 
              rotate: [0, 360],
              scale: [1, 1.1, 1]
            }}
            transition={{ 
              duration: 20, 
              repeat: Infinity, 
              ease: "linear" 
            }}
            className="p-3 bg-gradient-to-br from-yellow-400 to-yellow-600 rounded-xl shadow-xl"
          >
            <TrophyIcon className="h-8 w-8 text-black" />
          </motion.div>
          
          <div>
            <motion.h1 
              className="text-4xl md:text-6xl font-black leading-tight"
              animate={{ 
                backgroundPosition: ['0%', '100%', '0%']
              }}
              transition={{ 
                duration: 3,
                repeat: Infinity,
                ease: 'linear'
              }}
            >
              <span className="bg-gradient-to-r from-green-400 via-yellow-400 to-yellow-500 bg-clip-text text-transparent">
                FINAL DRAFT ORDER
              </span>
            </motion.h1>
            <motion.div 
              className="mt-2 flex items-center justify-center gap-2"
              animate={{ 
                backgroundPosition: ['0%', '100%', '0%']
              }}
              transition={{ 
                duration: 4,
                repeat: Infinity,
                ease: 'linear'
              }}
            >
              <div className="flex items-center gap-2 bg-gradient-to-r from-slate-800/50 to-slate-700/50 backdrop-blur-sm rounded-full px-4 py-2 border border-yellow-500/30">
                <span className="text-yellow-400 text-lg">🏆</span>
                <span className="text-sm font-bold bg-gradient-to-r from-yellow-400 via-orange-400 to-yellow-500 bg-clip-text text-transparent uppercase tracking-wider">
                  Fantasy Football 2025
                </span>
                <motion.div 
                  className="w-2 h-2 bg-yellow-400 rounded-full"
                  animate={{ 
                    opacity: [1, 0.3, 1],
                    scale: [1, 0.8, 1]
                  }}
                  transition={{ 
                    duration: 1.5,
                    repeat: Infinity,
                    ease: 'easeInOut'
                  }}
                />
              </div>
            </motion.div>
          </div>
          
          <motion.div 
            animate={{ 
              rotate: [0, -10, 10, 0],
              scale: [1, 1.1, 1]
            }}
            transition={{ 
              duration: 4,
              repeat: Infinity,
              ease: 'easeInOut'
            }}
            className="p-3 bg-gradient-to-br from-green-400 to-blue-500 rounded-xl shadow-xl"
          >
            <SparklesIcon className="h-8 w-8 text-white" />
          </motion.div>
        </div>
        
        {/* Results Complete Banner */}
        <div className="bg-gradient-to-r from-green-600 via-green-500 to-green-600 text-white px-6 py-3 rounded-full shadow-lg inline-block mb-6">
          <div className="flex items-center gap-2">
            <motion.div 
              className="w-2 h-2 bg-white rounded-full"
              animate={{ 
                scale: [1, 1.5, 1],
                opacity: [1, 0.5, 1]
              }}
              transition={{ duration: 1.5, repeat: Infinity }}
            />
            <span className="text-sm font-bold tracking-wide uppercase">Draft Order Complete</span>
            <motion.div 
              className="w-2 h-2 bg-white rounded-full"
              animate={{ 
                scale: [1, 1.5, 1],
                opacity: [1, 0.5, 1]
              }}
              transition={{ duration: 1.5, repeat: Infinity, delay: 0.75 }}
            />
          </div>
        </div>
        
        <motion.p 
          className="text-xl text-slate-200 max-w-2xl mx-auto font-medium"
          animate={{ opacity: [0.8, 1, 0.8] }}
          transition={{ duration: 3, repeat: Infinity }}
        >
          The destiny has been revealed! Here&apos;s your official fantasy football draft order.
        </motion.p>
      </motion.div>

      {/* Draft Order List */}
      <motion.div 
        className="backdrop-blur-xl bg-white/5 rounded-3xl p-8 border border-white/10 shadow-2xl mb-8"
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.2 }}
      >
        <div className="space-y-4">
          {sortedOrder.map((pick, index) => (
            <motion.div
              key={pick.id}
              className="relative group"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
            >
              {/* Position Banner */}
              <div className="flex items-center gap-6 p-6 rounded-2xl bg-gradient-to-r from-slate-800/50 to-slate-900/50 backdrop-blur border border-white/10 hover:border-orange-400/30 transition-all duration-300 group-hover:scale-[1.02]">
                
                {/* Position Number with Medal */}
                <div className="flex-shrink-0">
                  <div className={`w-20 h-20 rounded-full bg-gradient-to-br ${getPositionColor(pick.position)} flex items-center justify-center shadow-lg`}>
                    <span className="text-2xl font-black text-white">
                      #{pick.position}
                    </span>
                  </div>
                  <div className="text-center mt-2 text-2xl">
                    {getPositionEmoji(pick.position)}
                  </div>
                </div>

                {/* Member Info */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <h3 className="text-2xl font-bold text-white mb-1">{pick.name}</h3>
                      <p className="text-lg text-slate-300 font-medium">{pick.team}</p>
                    </div>
                    {pick.position === 1 && (
                      <motion.div
                        className="flex items-center gap-2 bg-yellow-400/20 text-yellow-400 px-3 py-1 rounded-full text-sm font-bold"
                        animate={{ scale: [1, 1.05, 1] }}
                        transition={{ duration: 2, repeat: Infinity }}
                      >
                        <TrophyIcon className="h-4 w-4" />
                        FIRST PICK!
                      </motion.div>
                    )}
                  </div>

                  {/* Details Grid */}
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div className="bg-white/5 rounded-lg p-3 border border-green-500/20">
                      <div className="text-xs font-bold text-transparent bg-gradient-to-r from-green-300 to-green-500 bg-clip-text uppercase tracking-wide mb-1">🎯 STRATEGY</div>
                      <div className="text-sm font-medium text-white">{pick.strategy}</div>
                    </div>
                    
                    <div className="bg-white/5 rounded-lg p-3 md:col-span-2 border border-blue-500/20">
                      <div className="text-xs font-bold text-transparent bg-gradient-to-r from-blue-300 to-blue-500 bg-clip-text uppercase tracking-wide mb-1">💪 TEAM MOTTO</div>
                      <div className="text-sm text-slate-300 italic font-medium">&quot;{pick.motto}&quot;</div>
                    </div>
                  </div>

                  {/* Prediction */}
                  <div className="mt-4 bg-gradient-to-r from-green-500/10 to-yellow-500/10 rounded-lg p-3 border border-green-500/30">
                    <div className="text-xs font-bold text-transparent bg-gradient-to-r from-purple-300 to-purple-500 bg-clip-text uppercase tracking-wide mb-1">🔮 SEASON PREDICTION</div>
                    <div className="text-sm text-green-100 font-medium italic">&quot;{pick.prediction}&quot;</div>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* Action Buttons */}
      <motion.div 
        className="text-center space-y-4"
        initial={{ opacity: 0, scale: 0.8 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.6, delay: 1 }}
      >
        <p className="text-lg text-slate-300 mb-6">
          🎊 May the best draft strategy win! Good luck this season! 🎊
        </p>
        
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          {/* PDF Export Button */}
          <motion.div
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
          >
            <Button
              onClick={exportToPDF}
              size="xl"
              variant="secondary"
              className="text-xl font-bold px-10 py-4 relative overflow-hidden group bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-500 hover:to-blue-600 text-white border-blue-500"
            >
              <motion.div
                className="absolute inset-0 bg-gradient-to-r from-blue-400 to-cyan-500 opacity-0 group-hover:opacity-20 transition-opacity duration-300"
              />
              <span className="relative z-10 flex items-center gap-3">
                <DocumentArrowDownIcon className="h-5 w-5" />
                Export to PDF
              </span>
            </Button>
          </motion.div>
          
          {/* Restart Button */}
          <motion.div
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
          >
            <Button
              onClick={onRestart}
              size="xl"
              variant="primary"
              className="text-xl font-bold px-10 py-4 relative overflow-hidden group"
            >
              <motion.div
                className="absolute inset-0 bg-gradient-to-r from-yellow-400 to-orange-500 opacity-0 group-hover:opacity-20 transition-opacity duration-300"
              />
              <span className="relative z-10 flex items-center gap-3">
                <ArrowPathIcon className="h-5 w-5" />
                Start New Draft Reveal
              </span>
            </Button>
          </motion.div>
        </div>

        {/* Draft Tips */}
        <motion.div 
          className="mt-12 p-6 bg-gradient-to-r from-green-500/10 to-yellow-500/10 rounded-2xl border border-green-500/20"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 1.5 }}
        >
          <h3 className="text-lg font-semibold text-green-200 mb-3">🧠 Draft Day Tips</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-green-100">
            <div>• Research player injury reports before drafting</div>
            <div>• Don&apos;t reach for your favorite team&apos;s players</div>
            <div>• Have backup plans for every position</div>
            <div>• Pay attention to bye weeks when drafting</div>
          </div>
        </motion.div>
      </motion.div>
    </div>
  );
}
